services:
  - type: web
    name: n8n-ai
    env: docker
    plan: free

    dockerfilePath: ./Dockerfile

    envVars:
      - key: N8N_HOST
        value: 0.0.0.0

      - key: N8N_PORT
        value: 5678

      - key: N8N_PROTOCOL
        value: https

      - key: WEBHOOK_URL
        value: https://n8n-ai.onrender.com/

      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata

      - key: N8N_ENABLE_EXECUTE_COMMAND
        value: true

      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: false

      - key: N8N_BASIC_AUTH_ACTIVE
        value: true

      - key: N8N_BASIC_AUTH_USER
        value: admin

      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin123
